checks:
    javascript: true
build:
    environment:
        variables:
            DB_TYPE: 'sqlite3'
            SQLITE_FILE: 'test.db'
            JWTSECRET: 'devMode'
            NODE_ENV: 'test'
    nodes:
        analysis:
            tests:
                override:
                    - command: eslint-run
                    - command: js-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: npm run db:migrate
                    - command: npm run db:seed
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
        tests: true
