build:
    environment:
        variables:
            DB_TYPE: 'sqlite3'
            SQLITE_FILE: 'test.db'
            JWTSECRET: 'devMode'
            NODE_ENV: 'test'
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests:
            override:
                - command: npm run db:migrate
                - command: npm run db:seed
                - command: npm test
