version: '3.1'

services:
    server:
        image: 'jsramverk-server'
        container_name: 'server'
        build:
            context: './'
            dockerfile: 'Dockerfile'
        ports:
            - 8081:8080
